(define (problem Ejercicio1)
    (:domain Ejercicio1-domain)
  (:objects z1 z2 z3 z4 z5 z6 z7 z8 z9 z10 z11 z12 z13 z14 z15 z16 z17 z18 z19 z20 z21 z22 z23 z24 z25 - zone
            player1 - player
            princesa principe bruja profesor leonardoDiCaprio - npc
            oscars manzanas algoritmos rosas oro zapatilla bikini - object
            north east south west - orientation
            bosque agua precipicio arena piedra - surface
			)
  (:init

  ;       23 24
  ; 19 20 21 22
  ; 18  1  2  3  4  5
  ; 17    25        6
  ; 16              7
  ; 15              8
  ; 14 13 12 11 10  9

    (orientedZone z1 east z2)
    (orientedZone z1 north z20)
    (orientedZone z1 west z18)
    (orientedZone z2 east z3)
    (orientedZone z2 west z1)
    (orientedZone z2 north z21)
    (orientedZone z2 south z25)
    (orientedZone z3 east z4)
    (orientedZone z3 west z2)
    (orientedZone z3 north z22)
    (orientedZone z4 east z5)
    (orientedZone z4 west z3)
    (orientedZone z5 south z6)
    (orientedZone z5 west z4)
    (orientedZone z6 north z5)
    (orientedZone z6 south z7)
    (orientedZone z7 north z6)
    (orientedZone z7 south z8)
    (orientedZone z8 north z7)
    (orientedZone z8 south z9)
    (orientedZone z9 north z8)
    (orientedZone z9 west z10)
    (orientedZone z10 east z9)
    (orientedZone z10 west z11)
    (orientedZone z11 east z10)
    (orientedZone z11 west z12)
    (orientedZone z12 east z11)
    (orientedZone z12 west z13)
    (orientedZone z13 west z14)
    (orientedZone z13 east z12)
    (orientedZone z14 north z15)
    (orientedZone z14 east z13)
    (orientedZone z15 north z16)
    (orientedZone z15 south z14)
    (orientedZone z16 north z17)
    (orientedZone z16 south z15)
    (orientedZone z17 north z18)
    (orientedZone z17 south z16)
    (orientedZone z18 north z19)
    (orientedZone z18 south z17)
    (orientedZone z18 east z1)
    (orientedZone z19 east z20)
    (orientedZone z19 south z18)
    (orientedZone z20 east z21)
    (orientedZone z20 west z19)
    (orientedZone z20 south z1)
    (orientedZone z21 east z22)
    (orientedZone z21 south z2)
    (orientedZone z21 west z20)
    (orientedZone z21 north z23)
    (orientedZone z22 north z24)
    (orientedZone z22 west z21)
    (orientedZone z22 south z3)
    (orientedZone z23 south z21)
    (orientedZone z23 east z24)
    (orientedZone z24 west z23)
    (orientedZone z24 south z22)
    (orientedZone z25 north z2)

    (typesurface z1 arena)
    (typesurface z2 piedra)
    (typesurface z3 arena)
    (typesurface z4 agua)
    (typesurface z5 arena)
    (typesurface z6 piedra)
    (typesurface z7 precipicio)
    (typesurface z8 piedra)
    (typesurface z9 agua)
    (typesurface z10 arena)
    (typesurface z11 piedra)
    (typesurface z12 piedra)
    (typesurface z13 arena)
    (typesurface z14 arena)
    (typesurface z15 piedra)
    (typesurface z16 arena)
    (typesurface z17 arena)
    (typesurface z18 bosque)
    (typesurface z19 arena)
    (typesurface z20 piedra)
    (typesurface z21 precipicio)
    (typesurface z22 arena)
    (typesurface z23 piedra)
    (typesurface z24 arena)
    (typesurface z25 agua)

    (= (distance z1 z2) 1)
    (= (distance z1 z20) 1)
    (= (distance z1 z18) 1)
    (= (distance z2 z3) 1)
    (= (distance z2 z1) 1)
    (= (distance z2 z21) 1)
    (= (distance z2 z25) 1)
    (= (distance z3 z4) 1)
    (= (distance z3 z2) 1)
    (= (distance z3 z22) 1)
    (= (distance z4 z5) 1)
    (= (distance z4 z3) 1)
    (= (distance z5 z6) 1)
    (= (distance z5 z4) 1)
    (= (distance z6 z5) 1)
    (= (distance z6 z7) 1)
    (= (distance z7 z6) 1)
    (= (distance z7 z8) 1)
    (= (distance z8 z7) 1)
    (= (distance z8 z9) 1)
    (= (distance z9 z8) 1)
    (= (distance z9 z10) 1)
    (= (distance z10 z9) 1)
    (= (distance z10 z11) 1)
    (= (distance z11 z10) 1)
    (= (distance z11 z12) 1)
    (= (distance z12 z11) 1)
    (= (distance z12 z13) 1)
    (= (distance z13 z14) 1)
    (= (distance z13 z12) 1)
    (= (distance z14 z15) 1)
    (= (distance z14 z13) 1)
    (= (distance z15 z16) 1)
    (= (distance z15 z14) 1)
    (= (distance z16 z17) 1)
    (= (distance z16 z15) 1)
    (= (distance z17 z16) 1)
    (= (distance z17 z18) 1)
    (= (distance z18 z19) 1)
    (= (distance z18 z17) 1)
    (= (distance z18 z1) 1)
    (= (distance z19 z20) 1)
    (= (distance z19 z18) 1)
    (= (distance z20 z21) 1)
    (= (distance z20 z19) 1)
    (= (distance z20 z1) 1)
    (= (distance z21 z22) 1)
    (= (distance z21 z2) 1)
    (= (distance z21 z20) 1)
    (= (distance z21 z23) 1)
    (= (distance z22 z24) 1)
    (= (distance z22 z21) 1)
    (= (distance z22 z3) 1)
    (= (distance z23 z21) 1)
    (= (distance z23 z24) 1)
    (= (distance z24 z23) 1)
    (= (distance z24 z22) 1)
    (= (distance z25 z2) 1)

    ;Puntos de Leonardo
    (= (objectScore oscars leonardoDiCaprio) 10)
    (= (objectScore rosas leonardoDiCaprio) 1)
    (= (objectScore manzanas leonardoDiCaprio) 3)
    (= (objectScore algoritmos leonardoDiCaprio) 4)
    (= (objectScore oro leonardoDiCaprio) 5)
    ;Puntos de la princesa
    (= (objectScore oscars princesa) 5)
    (= (objectScore rosas princesa) 10)
    (= (objectScore manzanas princesa) 1)
    (= (objectScore algoritmos princesa) 3)
    (= (objectScore oro princesa) 4)
    ;Puntos de la bruja
    (= (objectScore oscars bruja) 4)
    (= (objectScore rosas bruja) 5)
    (= (objectScore manzanas bruja) 10)
    (= (objectScore algoritmos bruja) 1)
    (= (objectScore oro bruja) 3)
    ;Puntos del profesor
    (= (objectScore oscars profesor) 3)
    (= (objectScore rosas profesor) 4)
    (= (objectScore manzanas profesor) 5)
    (= (objectScore algoritmos profesor) 10)
    (= (objectScore oro profesor) 1)
    ;Puntos del principe
    (= (objectScore oscars principe) 1)
    (= (objectScore rosas principe) 3)
    (= (objectScore manzanas principe) 4)
    (= (objectScore algoritmos principe) 5)
    (= (objectScore oro principe) 10)

    (= (total-distance) 0)
    (canTakeObject)
    (canPutObject)
    (= (totalScore) 0)

    (atPlayer player1 z12)
    (actualOrientation north player1)
    (atNPC princesa z22)
    (atNPC principe z5)
    (atNPC bruja z15)
    (atNPC profesor z1)
    (atNPC leonardoDiCaprio z3)
    (atObject manzanas z8)
    (atObject oscars z2)
    (atObject algoritmos z25)
    (atObject rosas z4)
    (atObject oro z16)
    (atObject bikini z3)
    (atObject zapatilla z14)
	 )
  (:goal (AND
              (>= (totalScore) 40) ;
         )
  )

  ;(:metric maximize (totalScore))
)
