(define (problem zeno-0)

(:domain zeno-travel)

(:customization
	(= :time-format "%d/%m/%Y %H:%M:%S")
	(= :time-horizon-relative 2500)
	(= :time-start "05/06/2007 08:00:00")
	(= :time-unit :hours)
)

(:objects
    p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 p28 - person
    Almeria Barcelona Bilbao Cadiz Cordoba Gibraltar Granada Jaen Madrid Malaga Seville - city
		a1 a2 - aircraft
)

; Max distance = 1284

(:init

	; DISTANCIAS
	(= (distance Almeria Barcelona) 809)
	(= (distance Almeria Bilbao) 958)
	(= (distance Almeria Cadiz) 463)
	(= (distance Almeria Cordoba) 316)
	(= (distance Almeria Gibraltar) 339)
	(= (distance Almeria Granada) 162)
	(= (distance Almeria Seville) 505)
	(= (distance Almeria Jaen) 220)
	(= (distance Almeria Madrid) 547)
	(= (distance Almeria Malaga) 207)
	(= (distance Almeria Seville) 410)
	(= (distance Barcelona Almeria) 809)
	(= (distance Barcelona Bilbao) 620)
	(= (distance Barcelona Cadiz) 1284)
	(= (distance Barcelona Cordoba) 908)
	(= (distance Barcelona Gibraltar) 1124)
	(= (distance Barcelona Granada) 868)
	(= (distance Barcelona Seville) 1140)
	(= (distance Barcelona Jaen) 804)
	(= (distance Barcelona Madrid) 621)
	(= (distance Barcelona Malaga) 997)
	(= (distance Barcelona Seville) 1046)
	(= (distance Bilbao Almeria) 958)
	(= (distance Bilbao Barcelona) 620)
	(= (distance Bilbao Cadiz) 1058)
	(= (distance Bilbao Cordoba) 796)
	(= (distance Bilbao Gibraltar) 1110)
	(= (distance Bilbao Granada) 829)
	(= (distance Bilbao Seville) 939)
	(= (distance Bilbao Jaen) 730)
	(= (distance Bilbao Madrid) 395)
	(= (distance Bilbao Malaga) 939)
	(= (distance Bilbao Seville) 933)
	(= (distance Cadiz Almeria) 463)
	(= (distance Cadiz Barcelona) 1284)
	(= (distance Cadiz Bilbao) 1058)
	(= (distance Cadiz Cordoba) 261)
	(= (distance Cadiz Gibraltar) 124)
	(= (distance Cadiz Granada) 296)
	(= (distance Cadiz Seville) 214)
	(= (distance Cadiz Jaen) 330)
	(= (distance Cadiz Madrid) 654)
	(= (distance Cadiz Malaga) 240)
	(= (distance Cadiz Seville) 126)
	(= (distance Cordoba Almeria) 316)
	(= (distance Cordoba Barcelona) 908)
	(= (distance Cordoba Bilbao) 765)
	(= (distance Cordoba Cadiz) 261)
	(= (distance Cordoba Gibraltar) 294)
	(= (distance Cordoba Granada) 160)
	(= (distance Cordoba Seville) 241)
	(= (distance Cordoba Jaen) 108)
	(= (distance Cordoba Madrid) 396)
	(= (distance Cordoba Malaga) 165)
	(= (distance Cordoba Seville) 143)
	(= (distance Gibraltar Almeria) 339)
	(= (distance Gibraltar Barcelona) 1124)
	(= (distance Gibraltar Bilbao) 1110)
	(= (distance Gibraltar Cadiz) 124)
	(= (distance Gibraltar Cordoba) 294)
	(= (distance Gibraltar Granada) 255)
	(= (distance Gibraltar Seville) 289)
	(= (distance Gibraltar Jaen) 335)
	(= (distance Gibraltar Madrid) 662)
	(= (distance Gibraltar Malaga) 134)
	(= (distance Gibraltar Seville) 201)
	(= (distance Granada Almeria) 162)
	(= (distance Granada Barcelona) 868)
	(= (distance Granada Bilbao) 829)
	(= (distance Granada Cadiz) 296)
	(= (distance Granada Cordoba) 160)
	(= (distance Granada Gibraltar) 255)
	(= (distance Granada Seville) 346)
	(= (distance Granada Jaen) 93)
	(= (distance Granada Madrid) 421)
	(= (distance Granada Malaga) 125)
	(= (distance Granada Seville) 252)
	(= (distance Seville Almeria) 505)
	(= (distance Seville Barcelona) 1140)
	(= (distance Seville Bilbao) 939)
	(= (distance Seville Cadiz) 214)
	(= (distance Seville Cordoba) 241)
	(= (distance Seville Gibraltar) 289)
	(= (distance Seville Granada) 346)
	(= (distance Seville Jaen) 347)
	(= (distance Seville Madrid) 591)
	(= (distance Seville Malaga) 301)
	(= (distance Seville Seville) 95)
	(= (distance Jaen Almeria) 220)
	(= (distance Jaen Barcelona) 804)
	(= (distance Jaen Bilbao) 730)
	(= (distance Jaen Cadiz) 330)
	(= (distance Jaen Cordoba) 108)
	(= (distance Jaen Gibraltar) 335)
	(= (distance Jaen Granada) 93)
	(= (distance Jaen Seville) 347)
	(= (distance Jaen Madrid) 335)
	(= (distance Jaen Malaga) 203)
	(= (distance Jaen Seville) 246)
	(= (distance Madrid Almeria) 547)
	(= (distance Madrid Barcelona) 621)
	(= (distance Madrid Bilbao) 395)
	(= (distance Madrid Cadiz) 654)
	(= (distance Madrid Cordoba) 396)
	(= (distance Madrid Gibraltar) 662)
	(= (distance Madrid Granada) 421)
	(= (distance Madrid Seville) 591)
	(= (distance Madrid Jaen) 335)
	(= (distance Madrid Malaga) 532)
	(= (distance Madrid Seville) 534)
	(= (distance Malaga Almeria) 207)
	(= (distance Malaga Barcelona) 997)
	(= (distance Malaga Bilbao) 939)
	(= (distance Malaga Cadiz) 240)
	(= (distance Malaga Cordoba) 165)
	(= (distance Malaga Gibraltar) 134)
	(= (distance Malaga Granada) 125)
	(= (distance Malaga Seville) 301)
	(= (distance Malaga Jaen) 203)
	(= (distance Malaga Madrid) 532)
	(= (distance Malaga Seville) 209)
	;^ DISTANCIAS ^

	(at p1 Madrid)
	(at p2 Madrid)
	(at p3 Bilbao)
	(at p4 Barcelona)
	(at p5 Granada)
	(at p6 Gibraltar)
	(at p7 Jaen)
	(at p8 Seville)
	(at p9 Barcelona)
	(at p10 Almeria)
	(at p11 Seville)
	(at p12 Barcelona)
	(at p13 Barcelona)
	(at p14 Barcelona)
	(at p15 Barcelona)
	(at p16 Barcelona)
	(at p17 Barcelona)
	(at p18 Barcelona)
	(at p19 Barcelona)
	(at p20 Barcelona)
	(at p21 Barcelona)
	(at p22 Barcelona)
	(at p23 Barcelona)
	(at p24 Barcelona)
	(at p25 Barcelona)
	(at p26 Barcelona)
	(at p27 Barcelona)
	(at p28 Barcelona)

  (at a1 Cordoba)
	(at a2 Jaen)

	(= (boarding-time) 1)
	(= (debarking-time) 1)

	(= (fuel a1) 2000) ;
	(= (slow-speed a1) 10)
	(= (fast-speed a1) 20)
	(= (slow-burn a1) 1)
	(= (fast-burn a1) 2)
	(= (total-fuel-used a1) 0)
	(= (fuel-limit a1) 30000)
	(= (capacity a1) 5136)
	(= (refuel-rate a1) 1)
	(= (numero-pasajeros a1) 0)
	(= (max-pasajeros a1) 4)
	(= (duracion a1) 0)
	(= (max-duracion a1) 40000)

	(= (fuel a2) 5136) ;Max distance(1284) * 4
	(= (slow-speed a2) 10)
	(= (fast-speed a2) 20)
	(= (slow-burn a2) 1)
	(= (fast-burn a2) 2)
	(= (total-fuel-used a2) 0)
	(= (fuel-limit a2) 100000)
	(= (capacity a2) 5136)
	(= (refuel-rate a2) 1)
	(= (numero-pasajeros a2) 0)
	(= (max-pasajeros a2) 1)
	(= (duracion a2) 0)
	(= (max-duracion a2) 150000)

	(destino p1 Granada)
	(destino p2 Jaen)
	(destino p3 Cordoba)
	(destino p4 Cordoba)
	(destino p5 Malaga)
	(destino p6 Seville)
	(destino p7 Madrid)
	(destino p8 Madrid)
	(destino p9 Madrid)
	(destino p10 Barcelona)
	(destino p11 Cadiz)
	(destino p12 Almeria)
	(destino p13 Almeria)
	(destino p14 Almeria)
	(destino p15 Almeria)
	(destino p16 Almeria)
	(destino p17 Almeria)
	(destino p18 Almeria)
	(destino p19 Almeria)
	(destino p20 Almeria)
	(destino p21 Almeria)
	(destino p22 Almeria)
	(destino p23 Almeria)
	(destino p24 Almeria)
	(destino p25 Almeria)
	(destino p26 Almeria)
	(destino p27 Almeria)
	(destino p28 Almeria)
)

(:tasks-goal :tasks((transport-person p1 Granada) (transport-person p3 Cordoba) (transport-person p4 Cordoba)
										(transport-person p5 Malaga) (transport-person p6 Seville) (transport-person p7 Madrid) (transport-person p8 Madrid)
										(transport-person p9 Madrid) (transport-person p10 Barcelona) (transport-person p11 Cadiz) (transport-person p12 Almeria)
										(transport-person p13 Almeria) (transport-person p14 Almeria) (transport-person p15 Almeria) (transport-person p16 Almeria)
										(transport-person p17 Almeria) (transport-person p18 Almeria) (transport-person p19 Almeria) (transport-person p20 Almeria)
										(transport-person p21 Almeria) (transport-person p22 Almeria) (transport-person p23 Almeria) (transport-person p24 Almeria)
										(transport-person p25 Almeria) (transport-person p26 Almeria) (transport-person p27 Almeria) (transport-person p28 Almeria)
									 )

)

)
